apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: name-lookup-solr-pv-volume
  spec:
    accessModes:
      - ReadWriteOnce
    capacity:
      storage: 50Gi
    nfs:
      path: /opt/translator-sri/name_lookup/solr
      server: stars-k-nfs.edc.renci.org
    persistentVolumeReclaimPolicy: Retain
    storageClassName: name-lookup-solr-pv

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: name-lookup-solr-pvc
    labels:
      type: local
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
    storageClassName: name-lookup-solr-pv
