apiVersion: v1
kind: Service
metadata:
  name: name-lookup-web
spec:
  type: LoadBalancer
  loadBalancerIP: ######### # replace with real ip
  selector:
    app:  name-lookup
  ports:
  - protocol: TCP
    port: 2433
    targetPort: 2433