# Kubernetes file for setting up a PVC to use for nameres-loading.
# 
# As of 2022dec11, this seems to come to 37G for files + 30G for snapshot.backup.
# I'm going to set the size to 150Gi so we have a bit of spare space if needed.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nameres-loading-solr
  labels:
    app: nameres-loading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: basic
